### ISSUE TITLE
Why are the masq_open_id_associations server_url and secret binary columns?

### ISSUE THREAD

**Issue by bardbess** [dennisreimann/masq#13]
I was having issues with the store_association method in lib/masq/active_record_openid_store/openid_ar_store.rb when trying to remove/create a record. A string would be passed back to the database but it was expecting a blob.

After changing the column to a string (varchar2 (Oracle) ) I haven't had any further issues.

Is there any reason the 'masq_open_id_associations' tables 'server_url' and 'secret' are binary column?

**Comment by dennisreimann** [comment]
Having them binary males them case sensitive in MySQL, I guess that's why.

**Comment by bardbess** [comment]
The secret column doesn't cause me any issues. Given that many browsers in fact are case insensitive when it comes to urls would you accept a pull request to change the column type provided the code round reading the data in and out takes this into consideration.

**Comment by dennisreimann** [comment]
Ye,s we could do that. However - it would be best if I could find a new maintainer for this project (see #12 for details), who can take care of things like that.

**Comment by bardbess** [comment]
I'm happy to help out where I can. It's a great project.

**Comment by dennisreimann** [comment]
@bardbess thanks for offering to step in. At first I'd like to get the people involved that have already contributed in the past - that said, I'd really like you to participate in the discussion here :)

**Comment by bardbess** [comment]
completely understand.

**Comment by bardbess** [comment]
forked. :)
