### ISSUE TITLE
Configuration comments & explanations

### ISSUE THREAD

**Issue by nogweii** [dennisreimann/masq#9]
So I'm not sure whether or not I understand what all of the options are in `config/masq.yaml`, so I spent some time commenting the default options in evaryont/fisheye@92c4079. Not sure if everything I said there is correct.

Could you please go through and do a quick lookthrough and confirm everything I've mentioned is accurate?

**Comment by dennisreimann** [comment]
Thanks, that looks good to me. Concerning the **protect_phishing** attribute: That's for requiring the user to go to the login page explicitly in case one is not logged in. If that feature is enabled, one will land on the `/safe-login` page and will have to go to the login page manually to ensure the right host is used.
